services:
  grafana-export-to-pdf:
    build: .
    container_name: grafana-export-to-pdf
    ports:
      - "3001:3001"
    volumes:
      - ./output:/usr/src/app/output
      - ./debug:/usr/src/app/debug
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      - EXPORT_SERVER_PORT=${EXPORT_SERVER_PORT:-3001}
